Updated var name
NafisKreatif/Mage-Way-For-Me pull request #2
Opened 2024-11-29 08:56 UTC by R27-04

updating variable name and edited a little bit so it wont so obvious that i copied someone script

2024-12-14 00:26 UTC, Cikang44 requested changes

2024-12-14 00:26 UTC, Cikang44 commented on Assets/Scripts/PlayerMovement/CharacterController2D.cs
> +    [SerializeField] private float _JumpForce = 400f;                            // Force added when the player jumps.
Dari standar penamaan baris ini "Private instance fields start with an underscore (_) and the remaining text is camelCased.
" huruf setelah underscore tidak kapital

2024-12-14 00:26 UTC, Cikang44 commented on Assets/Scripts/PlayerMovement/CharacterController2D.cs
>  public class CharacterController2D : MonoBehaviour
beri penjelasan class dalam komentar

2024-12-14 00:26 UTC, Cikang44 commented on Assets/Scripts/PlayerMovement/CharacterController2D.cs
> +    private void CheckGroundStatus()
Fungsi yang bukan dari MonoBehaviour dikasih comment penjelasan, also tolong kasih jarak antarfungsi biar rapih

2024-12-14 00:26 UTC, Cikang44 commented on Assets/Scripts/PlayerMovement/CharacterController2D.cs
>      public void Move(float move, bool jump)
Kasih komentar penjelasan

2024-12-14 00:26 UTC, Cikang44 commented on Assets/Scripts/PlayerMovement/CharacterController2D.cs
>      private void Flip()
Kasih komentar penjelasan

2024-12-14 00:26 UTC, Cikang44 commented on Assets/Scripts/PlayerMovement/PlayerMovement.cs
>  public class PlayerMovement : MonoBehaviour
Kasih komentar penjelasan

2024-12-14 00:27 UTC, Cikang44 commented
FYI, buat commit baru utk memperbaiki hal2 tersebut, push, lalu pencet "Resolve Conversation" utk setiap review

2024-12-18 16:10 UTC, R27-04 commented
i already comment and update the variable name,

2025-01-10 02:31 UTC, Cikang44 approved these changes

2025-01-10 04:42 UTC, closed without merging